/**
 * The console's icon set: Phosphor, one family, one weight, imported through this module so a
 * screen never reaches for a second icon library or hand-rolls an SVG path.
 */
export {
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowsClockwise,
  Bell,
  Buildings,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Megaphone,
  ChatCircleText,
  PushPin,
  Check,
  Coins,
  Copy,
  ClipboardText,
  Cloud,
  Cube,
  Database,
  GaugeIcon as Gauge,
  Gear,
  GraphicsCard,
  Hammer,
  HardDrives,
  Hourglass,
  Link as LinkIcon,
  List,
  LockKey,
  MagnifyingGlass,
  Moon,
  Package,
  Plus,
  Question,
  SidebarSimple,
  SignOut,
  SquaresFour,
  Sun,
  Tag,
  Tray,
  UserCircle,
  UsersThree,
  Warning,
  SlidersHorizontal,
  ShieldCheck,
  Pulse,
  ChartLine,
  Stack,
  User,
  Monitor,
  X, DownloadSimple,
} from '@phosphor-icons/react';
